import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { scaffold, newFeature, register, labConfig, renderRegistry, findVariants } from '../scripts/design-lab.mjs';
import { planScaffold, applyScaffold } from '../scripts/scaffold.mjs';
import { detect } from '../scripts/detect.mjs';
import { fixtureCopy, runScript } from './helpers.mjs';

const read = (cwd, f) => fs.readFileSync(path.join(cwd, f), 'utf8');
const ROUTE = 'app/__design-lab/[feature].tsx';

test('scaffold creates route, host and registry (once) and reports the root layout mount', () => {
  const cwd = fixtureCopy('expo-router-app');
  const first = scaffold(cwd);
  assert.deepEqual(first.map((r) => [r.path, r.action]), [
    [ROUTE, 'created'], ['src/design-lab/DesignLabHost.tsx', 'created'], ['src/design-lab/registry.ts', 'created'], ['app/_layout.tsx', 'todo'], ['package.json', 'todo'],
  ]);
  assert.match(first[3].todo, /import \{ DesignLabHost \} from '\.\.\/src\/design-lab\/DesignLabHost';/);
  assert.match(read(cwd, ROUTE), /__DEV__ \|\| process\.env\.EXPO_PUBLIC_DESIGN_LAB === '1'/);
  assert.match(read(cwd, 'src/design-lab/DesignLabHost.tsx'), /from '\.\/registry'/);
  assert.match(read(cwd, 'src/design-lab/DesignLabHost.tsx'), /useURL\(\)/);
  assert.ok(first.some((r) => r.path === 'package.json' && /expo-linking/.test(r.todo)), 'fixture has no expo-linking');
  fs.writeFileSync(path.join(cwd, 'app/_layout.tsx'), "import { DesignLabHost } from '../src/design-lab/DesignLabHost';\nexport default () => (<><Stack /><DesignLabHost /></>);\n");
  assert.equal(scaffold(cwd).find((r) => r.path === 'app/_layout.tsx').action, 'host mounted');
  fs.writeFileSync(path.join(cwd, ROUTE), '// customised\n');
  assert.equal(scaffold(cwd)[0].action, 'exists');
  assert.equal(read(cwd, ROUTE), '// customised\n');
});

test('new creates stubs, never overwrites, and registers them', () => {
  const cwd = fixtureCopy('expo-router-app');
  scaffold(cwd);
  newFeature(cwd, 'trip-details', ['A', 'B']);
  assert.match(read(cwd, 'src/design-lab/trip-details/VariantA.tsx'), /^\/\/ A: <one-line thesis/);
  assert.match(read(cwd, 'src/design-lab/trip-details/VariantB.tsx'), /export default function TripDetailsVariantB/);
  fs.writeFileSync(path.join(cwd, 'src/design-lab/trip-details/VariantA.tsx'), '// A: mine\nexport default () => null;\n');
  const again = newFeature(cwd, 'trip-details', ['A', 'B', 'C']);
  assert.deepEqual(again.filter((r) => r.path.includes('Variant')).map((r) => r.action), ['exists', 'unchanged', 'created']);
  assert.match(read(cwd, 'src/design-lab/trip-details/VariantA.tsx'), /mine/);
  assert.match(read(cwd, 'src/design-lab/registry.ts'), /'trip-details': \{ A: TripDetailsA, B: TripDetailsB, C: TripDetailsC \}/);
});

test('register reflects deleted variants and is idempotent', () => {
  const cwd = fixtureCopy('expo-router-app');
  scaffold(cwd);
  newFeature(cwd, 'onboarding', ['A', 'B', 'C']);
  fs.rmSync(path.join(cwd, 'src/design-lab/onboarding/VariantC.tsx'));
  assert.equal(register(cwd)[0].action, 'updated');
  assert.deepEqual(findVariants(cwd, 'src/design-lab'), { onboarding: ['A', 'B'] });
  assert.equal(register(cwd)[0].action, 'unchanged');
  fs.rmSync(path.join(cwd, 'src/design-lab/onboarding'), { recursive: true });
  assert.doesNotMatch((register(cwd), read(cwd, 'src/design-lab/registry.ts')), /onboarding/);
});

test('renderRegistry output', () => {
  assert.equal(renderRegistry({ a: ['A'] }), [
    '// Generated by mobile-kit (scripts/design-lab.mjs register). Do not edit by hand.',
    "import type { ComponentType } from 'react';",
    "import AA from './a/VariantA';",
    '',
    'export const designLab: Record<string, Record<string, ComponentType>> = {',
    "  'a': { A: AA },",
    '};',
    '',
  ].join('\n'));
});

test('invalid names are rejected; projects without expo-router are refused', () => {
  const cwd = fixtureCopy('expo-router-app');
  assert.throws(() => newFeature(cwd, 'Bad Name', ['A']), /kebab-case/);
  assert.throws(() => newFeature(cwd, 'ok', ['a']), /capital letters/);
  assert.throws(() => scaffold(fixtureCopy('bare-rn-app')), /needs expo-router/);
});

test('config: lab screens with chrome=0, small/standard + font-200, one iPhone, base untouched', () => {
  const cwd = fixtureCopy('expo-router-app');
  applyScaffold(planScaffold({ cwd, det: detect(cwd, { expoCli: false }), modules: ['matrix'] }), cwd);
  const before = read(cwd, 'qa/device-matrix.json');
  const r = labConfig(cwd, 'onboarding', ['A', 'B'], 'qa/device-matrix.json');
  assert.equal(r.path, 'qa-shots/design-lab/onboarding.json');
  const cfg = JSON.parse(read(cwd, r.path));
  assert.deepEqual(cfg.screens, [
    { name: 'onboarding-A', path: '__design-lab/onboarding?v=A&chrome=0' },
    { name: 'onboarding-B', path: '__design-lab/onboarding?v=B&chrome=0' },
  ]);
  assert.deepEqual(cfg.android.profiles.map((p) => p.name), ['small-360', 'standard-411']);
  assert.deepEqual(cfg.android.stress, { profile: 'small-360', variants: [{ name: 'font-200', fontScale: 2 }] });
  assert.deepEqual(cfg.ios.devices.map((d) => d.name), ['base']);
  assert.equal(cfg.ios.stress, undefined);
  assert.equal(cfg.app.scheme, 'fixture');
  assert.equal(read(cwd, 'qa/device-matrix.json'), before);
  assert.throws(() => labConfig(cwd, 'x', ['A'], 'qa/missing.json'), /not found/);
});

test('CLI', () => {
  const cwd = fixtureCopy('expo-router-app');
  assert.equal(runScript('design-lab.mjs', ['scaffold', '--cwd', cwd]).code, 0);
  const r = runScript('design-lab.mjs', ['new', '--feature', 'home', '--variants', 'A,B', '--cwd', cwd, '--json']);
  assert.equal(r.json.files.filter((f) => f.action === 'created').length, 2);
  assert.equal(runScript('design-lab.mjs', ['new', '--cwd', cwd]).code, 1);
  assert.equal(runScript('design-lab.mjs', ['config', '--feature', 'home', '--cwd', cwd]).code, 1, 'no base config yet');
  assert.match(runScript('design-lab.mjs', ['--help']).stdout, /Usage: node design-lab.mjs/);
});
