#!/usr/bin/env node
// Design Lab helper for the design-proposals skill: route scaffold, variant stubs, registry, matrix config.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs, handleHelp, list } from './lib/args.mjs';
import { KIT_ROOT, LOCK_FILE, exists, isDir, readJson, readText, writeText, writeJson } from './lib/fs.mjs';
import { log, printJson, setJsonMode, die } from './lib/log.mjs';
import { detect } from './detect.mjs';

const HELP = `
Usage: node design-lab.mjs <command> [options]

Commands:
  scaffold                      Create the lab route, <src>/design-lab/DesignLabHost.tsx and the registry (once),
                                and report whether the root layout mounts <DesignLabHost />
  new --feature <name>          Create Variant stubs in <src>/design-lab/<feature>/ and update the registry
      [--variants A,B,C]        (default A,B,C; existing files are never overwritten)
  register                      Regenerate <src>/design-lab/registry.ts from the variant folders
  config --feature <name>       Write a matrix config for the variants to qa-shots/design-lab/<feature>.json
      [--variants A,B,C] [--base qa/device-matrix.json]
      Profiles: Android small-360 + standard-411 (+ font-200 on small-360), iOS one iPhone ("base").

Options:
  --cwd <dir>   Project root (default: current directory)
  --json        JSON result on stdout
  --help        Show this help
`;

const ASSETS = path.join(KIT_ROOT, 'skills', 'design-proposals', 'assets');
const FEATURE_RE = /^[a-z][a-z0-9-]*$/;
const VARIANT_RE = /^[A-Z]$/;

/** Where things live in this project. */
export function layout(cwd) {
  const det = detect(cwd, { expoCli: false });
  if (!det.ok) throw new Error(det.error);
  if (!det.router || !det.routesRoot) throw new Error('Design Lab needs expo-router (no app/ or src/app/ routes found). Add a dev-only screen by hand instead.');
  const labDir = det.srcDir ? 'src/design-lab' : 'design-lab';
  return {
    det, routesRoot: det.routesRoot, labDir,
    route: `${det.routesRoot}/__design-lab/[feature].tsx`,
    host: `${labDir}/DesignLabHost.tsx`,
    registry: `${labDir}/registry.ts`,
    rootLayout: ['tsx', 'ts', 'jsx', 'js'].map((e) => `${det.routesRoot}/_layout.${e}`).find((f) => exists(path.join(cwd, f))) ?? null,
  };
}

const pascal = (s) => s.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const relImport = (fromFile, toFile) => {
  let r = path.posix.relative(path.posix.dirname(fromFile), toFile.replace(/\.tsx?$/, ''));
  return r.startsWith('.') ? r : './' + r;
};

/** Variants on disk: { feature: ['A','B',...] }. */
export function findVariants(cwd, labDir) {
  const abs = path.join(cwd, labDir);
  const out = {};
  if (!isDir(abs)) return out;
  for (const feature of fs.readdirSync(abs).sort()) {
    if (!FEATURE_RE.test(feature) || !isDir(path.join(abs, feature))) continue;
    const letters = fs.readdirSync(path.join(abs, feature)).map((f) => f.match(/^Variant([A-Z])\.[tj]sx$/)?.[1]).filter(Boolean).sort();
    if (letters.length) out[feature] = letters;
  }
  return out;
}

export function renderRegistry(variants) {
  const imports = [];
  const entries = [];
  for (const [feature, letters] of Object.entries(variants)) {
    const parts = letters.map((l) => {
      const id = `${pascal(feature)}${l}`;
      imports.push(`import ${id} from './${feature}/Variant${l}';`);
      return `${l}: ${id}`;
    });
    entries.push(`  '${feature}': { ${parts.join(', ')} },`);
  }
  return [
    '// Generated by mobile-kit (scripts/design-lab.mjs register). Do not edit by hand.',
    "import type { ComponentType } from 'react';",
    ...imports,
    '',
    'export const designLab: Record<string, Record<string, ComponentType>> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

function writeIfChanged(cwd, rel, content, results, { overwrite = true } = {}) {
  const abs = path.join(cwd, rel);
  const cur = readText(abs);
  if (cur === content) return results.push({ path: rel, action: 'unchanged' });
  if (cur != null && !overwrite) return results.push({ path: rel, action: 'exists' });
  writeText(abs, content);
  results.push({ path: rel, action: cur == null ? 'created' : 'updated' });
}

export function register(cwd, results = []) {
  const { labDir, registry } = layout(cwd);
  writeIfChanged(cwd, registry, renderRegistry(findVariants(cwd, labDir)), results);
  return results;
}

/** Whether the root layout mounts the host, and the lines to add if not. */
export function hostStatus(cwd) {
  const { rootLayout, host } = layout(cwd);
  if (!rootLayout) return { mounted: false, rootLayout: null, todo: 'No root _layout file found: render <DesignLabHost /> at the top of the app tree.' };
  const text = readText(path.join(cwd, rootLayout)) ?? '';
  const importLine = `import { DesignLabHost } from '${relImport(rootLayout, host)}';`;
  const mounted = /<DesignLabHost\s*\/>/.test(text);
  return {
    mounted,
    rootLayout,
    importLine,
    todo: mounted ? null : `Mount the host in ${rootLayout}: add \`${importLine}\` and render <DesignLabHost /> as the LAST child of the root element (after the navigator) so it draws on top.`,
  };
}

export function scaffold(cwd) {
  const { route, host } = layout(cwd);
  const results = [];
  writeIfChanged(cwd, route, readText(path.join(ASSETS, 'DesignLab.template.tsx')), results, { overwrite: false });
  writeIfChanged(cwd, host, readText(path.join(ASSETS, 'DesignLabHost.template.tsx')), results, { overwrite: false });
  register(cwd, results);
  const st = hostStatus(cwd);
  results.push({ path: st.rootLayout ?? '(root layout)', action: st.mounted ? 'host mounted' : 'todo', ...(st.todo ? { todo: st.todo } : {}) });
  const pkg = readJson(path.join(cwd, 'package.json')) ?? {};
  if (!{ ...pkg.dependencies, ...pkg.devDependencies }['expo-linking'])
    results.push({ path: 'package.json', action: 'todo', todo: 'The host reads the incoming URL with expo-linking: npx expo install expo-linking' });
  return results;
}

export function newFeature(cwd, feature, letters) {
  if (!FEATURE_RE.test(feature)) throw new Error(`--feature must be kebab-case (got "${feature}")`);
  const bad = letters.filter((l) => !VARIANT_RE.test(l));
  if (bad.length) throw new Error(`Variants must be single capital letters (got ${bad.join(', ')})`);
  const { labDir, route } = layout(cwd);
  const results = [];
  const tpl = readText(path.join(ASSETS, 'Variant.template.tsx'));
  for (const l of letters) {
    const content = tpl.replaceAll('{{letter}}', l).replaceAll('{{feature}}', feature).replaceAll('{{component}}', `${pascal(feature)}Variant${l}`);
    writeIfChanged(cwd, `${labDir}/${feature}/Variant${l}.tsx`, content, results, { overwrite: false });
  }
  register(cwd, results);
  if (!exists(path.join(cwd, route))) results.push({ path: route, action: 'missing (run scaffold)' });
  return results;
}

export function labConfig(cwd, feature, letters, basePath) {
  const base = readJson(path.join(cwd, basePath));
  if (!base) throw new Error(`Base matrix config not found: ${basePath} (run /mobile-kit:init)`);
  const cfg = structuredClone(base);
  cfg.screens = letters.map((l) => ({ name: `${feature}-${l}`, path: `__design-lab/${feature}?v=${l}&chrome=0` }));
  const small = cfg.android?.profiles?.find((p) => p.name === 'small-360');
  const standard = cfg.android?.profiles?.find((p) => p.name === 'standard-411');
  if (!small || !standard) throw new Error('The base config needs the small-360 and standard-411 Android profiles');
  cfg.android.profiles = [small, standard].map(({ optional, ...p }) => p);
  const font200 = cfg.android.stress?.variants?.find((v) => v.name === 'font-200') ?? { name: 'font-200', fontScale: 2.0 };
  cfg.android.stress = { profile: 'small-360', variants: [font200] };
  const iphone = cfg.ios?.devices?.find((d) => d.name === 'base') ?? cfg.ios?.devices?.find((d) => !d.optional);
  if (cfg.ios) { cfg.ios.devices = iphone ? [{ ...iphone, optional: undefined }] : []; delete cfg.ios.stress; }
  const out = `qa-shots/design-lab/${feature}.json`;
  writeJson(path.join(cwd, out), cfg);
  return { path: out, screens: cfg.screens.map((s) => s.name), android: cfg.android.profiles.map((p) => p.name).concat('small-360+font-200'), ios: cfg.ios?.devices?.map((d) => d.name) ?? [] };
}

export function main(argv) {
  const args = parseArgs(argv, { boolean: ['json', 'help'], string: ['cwd', 'feature', 'variants', 'base'], alias: { h: 'help' } });
  handleHelp(args, HELP);
  setJsonMode(args.json);
  const cwd = path.resolve(args.cwd || '.');
  const [cmd] = args._;
  const letters = args.variants ? list(args.variants) : ['A', 'B', 'C'];
  let result;
  try {
    if (cmd === 'scaffold') result = { files: scaffold(cwd) };
    else if (cmd === 'register') result = { files: register(cwd) };
    else if (cmd === 'new') { if (!args.feature) die('new needs --feature <name>'); result = { files: newFeature(cwd, args.feature, letters) }; }
    else if (cmd === 'config') {
      if (!args.feature) die('config needs --feature <name>');
      const base = args.base || readJson(path.join(cwd, LOCK_FILE))?.configPath || 'qa/device-matrix.json';
      result = { config: labConfig(cwd, args.feature, letters, base) };
    } else { process.stdout.write(HELP.trim() + '\n'); return cmd ? 1 : 0; }
  } catch (e) { die(e.message); }
  if (args.json) printJson(result);
  else if (result.files) for (const f of result.files) log.info(`${f.action === 'created' || f.action === 'updated' ? '✔' : f.action === 'todo' ? '!' : '·'} ${f.path}: ${f.todo ?? f.action}`);
  else log.ok(`${result.config.path}: screens ${result.config.screens.join(', ')}; android ${result.config.android.join(', ')}; ios ${result.config.ios.join(', ') || 'none'}`);
  return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) process.exit(main(process.argv.slice(2)));
